apiVersion: v1
kind: Service
metadata:
  name: automated-maintenance-suite-service
spec:
  type: NodePort
  selector:
    app: automated-maintenance-suite
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007  # you can use any free port between 30000-32767
